# Generated by Django 4.2.5 on 2024-02-13 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_alter_review_rating'),
        ('transaction', '0002_alter_transaction_transaction_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_buyer',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='subtotal',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='number_identifier',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_item',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_quantity',
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='market.product'),
        ),
    ]
