# Generated by Django 4.2.5 on 2023-09-14 14:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('productType', models.CharField(choices=[('Processor', 'Processor'), ('Motherboard', 'Motherboard'), ('PSU', 'PSU'), ('GPU', 'GPU'), ('RAM', 'RAM'), ('Storage', 'Storage'), ('Case', 'Case'), ('Peripherals', 'Peripherals'), ('Cooler', 'Cooler'), ('Other', 'Other')], default='Other', max_length=30)),
                ('description', models.TextField(blank=True, default="User hasn't described the product yet.", max_length=1000, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(blank=True, default='defaultProductImage.png', null=True, upload_to='products_images')),
                ('averageRating', models.FloatField(default=0)),
                ('availability', models.CharField(blank=True, choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=30, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users_wishlist', models.ManyToManyField(blank=True, related_name='users_wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('rating', models.FloatField(default=0)),
                ('comment', models.TextField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='market.product')),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
    ]
