# Generated by Django 4.2.5 on 2023-09-15 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_product_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Images',
            new_name='ProductImages',
        ),
    ]
