# Generated by Django 4.2.5 on 2023-09-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_rename_picture_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
