# Generated by Django 4.2.5 on 2023-11-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
        migrations.RemoveField(
            model_name='cart',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
    ]
